Dockerize application and fix CI flow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,10 +23,19 @@ jobs:
       - name: Build application
         run: npm run build
 
+      - name: Build Docker Image
+        run: docker build -t combat-connect-app-dev .
+
+      - name: Start Docker Containers
+        run: |
+          set -e
+          docker-compose up -d || { echo 'Docker Compose failed.' ; exit 1; }
+
       - name: Run tests
         run: npm test
-        needs: Build application
 
       - name: Run linter
         run: npm run lint
-        needs: Build application
+
+      - name: Stop Docker Containers
+        run: docker-compose down
